include LatoCore::Interface

# This file contains list of informations for the application.

CORE_NAVIGATION = core_getNavbarItems
CORE_APPNAME = core_getApplicationName
CORE_APPURL = core_getApplicationURL
CORE_APPLOGINROOT = core_getApplicationLoginRoot
CORE_APPLANGUAGES = core_getApplicationLanguages
CORE_APPSERVICEMAIL = core_getApplicationServiceEmail
CORE_SUPERUSERSHIDESETTINGS = core_getHideUsersSettings
CORE_SUPERUSERSPERMISSIONSHIDESETTINGS = core_getHideUsersPermissionsSettings
CORE_SUPERUSERSPERMISSIONSNAMESSETTINGS = core_getUsersPermissionsNamesSettings
CORE_RECOVERYPASSWORDPERMISSION = core_getRecoveryPasswordPermission
