# Set the application name

app_name: Lato

# Add custom voices to the sidebar

# menu:
#   example:
#     name: Menu voice
#     url: "/"
#     icon: home
#     position: 1
#     permission: 0

# Add custom assets to the layout

# assets:
#   style:
#     url: application
#     type: css
#   code:
#     url: application
#     type: js

# Set languages used by the applications (if it has more languages)

# languages: it, en

# Set application root url (default 'localhost')

# root_url: http://localhost:3000

# Set the application service email

# service_email: service@lato.com

# Set custom page after login

# login_home: "/example"

# Hide users with permission value to users with others permission value

# hide_users: 1 to 2, 4 to 6
