# Basic informations
# -----------------------------------------------------------------------------
# Please, set a correct value for these informations

# Set the application name
app_name: Lato

# Set languages used by the applications (if it has more languages)
languages: it

# Set application root url (default 'localhost')
root_url: http://localhost:3000

# Set the application service email
service_email: service@lato.com

# Usage informations
# -----------------------------------------------------------------------------

# Add custom voices to the sidebar
# menu:
#   example:
#     name: Menu voice
#     url: "/"
#     icon: home
#     position: 1
#     permission: 0

# Set custom page after login
# login_home: "/example"

# Users settings
# -----------------------------------------------------------------------------

# Hide users with permission value to users with others permission value
# hide_users: 1 to 2, 4 to 6

# Rename users permission from number to text value
# rename_users_permissions: 1 - Client, 5 - Operator

# Hide users permissions on users form
# hide_users_permissions: 2, 3, 4
