# WELCOME MESSAGE
welcome: Benvenuto nel pannello di amministrazione di

# VOCABOLARY
vocabolary:
  dashboard: Dashboard
  users: Utenti
  name: Nome
  username: Username
  email: Email
  permission: Permessi
  password: Password
  password_confirmation: Conferma password
  edit: Modifica utente
  new: Nuovo utente
  save: Salva
  send: Invia
  login: Login
  password_forget: Password dimenticata

# FORMS
forms:
  base_informations: Informazioni base
  user_password: Password dell'utente
  password_edit_settings: Lasciare il campo vuoto per non modificare la password

# SUPERUSERS
superusers:
  not_found: L'utente cercato non esiste
  success_create: L'utente è stato creato con successo
  failed_create: L'utente non è stato creato poichè alcuni dati non sono stati inseriti o non sono corretti
  permission_create: Non puoi creare un utente con permessi superiori ai tuoi
  success_update: L'utente è stato modificato correttamente
  failed_update: L'utente non è stato modificato poichè alcuni dati non sono stati inseriti o non sono corretti
  permission_update: Non puoi modificare un utente con permessi superiori o uguali ai tuoi
  level_update: Non puoi aumentarti il livello da solo. Per farlo devi chiedere ad un utente con permessi maggiori
  admin_update: L'utente amministratore non può essere modificato da nessuno
  success_destroy: L'utente è stato eliminato correttamente
  failed_destroy: L'utente non è stato eliminato a causa di un errore
  itself_destroy: Non puoi eliminare te stesso
  permission_destroy: Non puoi eliminare un utente con permessi superiori o uguali ai tuoi
  login_error: Username o password errati

# RECOVER_PASSWORD
recover_password:
  recover_guide: Inserisci il tuo indirizzo email. Riceverai un nuovo messaggio che ti guiderà alla registrazione di una nuova password.
  recover_guide_psw: Inserisci la nuova password due volte per aggiornare i tuoi dati di accesso
  confirm_send: Un email è stata inviata al tuo indirizzo
  email_subject: Recupero password dimenticata
  email_intestation: Abbiamo ricevuto una richiesta di recupero password per questo indirizzo email
  email_guide: Se non ha richiesto il recupero della password ignori questa email. Per creare una nuova password segua il seguente link. Il link ha una validità massima di 24 ore.
  recover_error_user: L'utente per il quale recuperare la password non esiste
  recover_error_token: Il token di sicurezza non risulta avere il formato corretto
  recover_error_token_time: Il token di sicurezza risulta scaduto. Richiedi nuovamente il recupero della password
  recover_error: Il recupero non è avvenuto a causa di un errore
  recover_success: L'aggiornamento della password è avvenuto correttamente

# MAILERS
mailers:
  notify_subject: Nuova notifica da
